CREATE TABLE users (
    ID UUID PRIMARY KEY,
    Username VARCHAR(50) UNIQUE NOT NULL,
    PasswordHash TEXT NOT NULL
);

CREATE TABLE todos
(
    ID SERIAL PRIMARY KEY,
    Title VARCHAR(50) NOT NULL,
    Description TEXT,
    Tags VARCHAR(50)[],
    DueTime date,
    UserId UUID REFERENCES users(ID) ON DELETE CASCADE
);

CREATE TABLE refresh_tokens
(
    ID SERIAL PRIMARY KEY,
    TOKEN TEXT NOT NULL,
    ExpiryDate TIMESTAMPTZ NOT NULL,
    CreatedAt TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UserId UUID REFERENCES users(id) ON DELETE CASCADE
)