env: "local" # local, prod

server:
  port: "8888"

database:
  host: "localhost"
  port: "5432"
  name: "todoapi"
  user: "postgres"
  password: "postgres"

token:
  accessTokenSecret: "secret_access"
  refreshTokenSecret: "secret_refresh"
  accessTokenExpire: 15 # 15 minute
  refreshTokenExpire: 10080 # 10080 minute = 7 days